dist: trusty
sudo: required
language: python
matrix:
  include:
    - python: 2.7
      env: JUJU_VERSION=1
    - python: 3.5
      env: JUJU_VERSION=2
install:
  - .travis/install.sh
  - pip install -r test-requires.txt python-coveralls -e .
before_script:
  - ./.travis/bootstrap.sh
script:
  - nosetests -v --nologcapture --with-coverage --cover-package=amulet
after_success:
  - coveralls
after_script:
  - ./.travis/cleanup.sh
